name: "Publish"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Initialize Actions
        uses: actions/checkout@v2
        with:
          token: ${{ steps.get_token.outputs.token }}

      - run: |
          # Update the Version in the plugin file
          sed -i "s/Version: VERSION\+/Version: ${{ github.ref_name }}/g" wp-openid.php

      - run: mkdir build

      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r build/wp-openid.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build**

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wp-openid
          path: build/wp-openid.zip

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          generateReleaseNotes: true
          token: ${{ steps.generate_token.outputs.token }}
          artifacts: build/wp-openid.zip
          replacesArtifacts: true

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
          token: ${{ steps.generate_token.outputs.token }}
