name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: mkdir build

      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r build/wp-openid.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build**

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wp-openid
          path: build/wp-openid.zip

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/wp-openid.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}